// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaeFFedvQ92MBexS2C33HQDYi48uLzTgE',
    appId: '1:880386658836:web:a3a6e9e1679c2f27fd0d01',
    messagingSenderId: '880386658836',
    projectId: 'fip9-a1a20',
    authDomain: 'fip9-a1a20.firebaseapp.com',
    storageBucket: 'fip9-a1a20.firebasestorage.app',
    measurementId: 'G-MM6GDM4BVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswXHnDIoMTrAj2Zy89PNKKkBh3mxjEIM',
    appId: '1:880386658836:android:35399b51977ff36cfd0d01',
    messagingSenderId: '880386658836',
    projectId: 'fip9-a1a20',
    storageBucket: 'fip9-a1a20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJ8UTk0HHz9xInLGJs2dQ8WXYU26eWuA',
    appId: '1:880386658836:ios:65c6378c9d894c01fd0d01',
    messagingSenderId: '880386658836',
    projectId: 'fip9-a1a20',
    storageBucket: 'fip9-a1a20.firebasestorage.app',
    iosBundleId: 'com.stepbystep.fip9.fip9',
  );

}